CREATE DATABASE PaperReviews;

USE PaperReviews;

CREATE TABLE AUTHOR (EmailAddr VARCHAR(50) NOT NULL, FirstName VARCHAR(50) NOT NULL, LastName VARCHAR(50) NOT NULL, PRIMARY KEY (EmailAddr));

CREATE TABLE PAPER (Id INT NOT NULL AUTO_INCREMENT, Title VARCHAR(100), Abstract TEXT, FileName VARCHAR(25), PRIMARY KEY(Id));

CREATE TABLE REVIEWER (ReviewerEmailAddr VARCHAR(50), FirstName VARCHAR(50), LastName VARCHAR(50), PhoneNum VARCHAR(50), AuthorFeedback TEXT NOT NULL, CommiteeFeedback TEXT NOT NULL, Affiliation TEXT, PRIMARY KEY (ReviewerEmailAddr));

CREATE TABLE TOPIC (Id INT NOT NULL AUTO_INCREMENT, TopicName VARCHAR(100), FOREIGN KEY (Id) REFERENCES PAPER(Id));

CREATE TABLE REVIEW (Id INT NOT NULL AUTO_INCREMENT, MeritScore INT, PaperId INT NOT NULL, ReviewerId VARCHAR(50) NOT NULL, ReadabilityScore INT, RelevanceScore INT, OriginalityScore INT, Recommendation MEDIUMTEXT, PRIMARY KEY (Id), FOREIGN KEY (PaperId) REFERENCES PAPER(Id), FOREIGN KEY (ReviewerID) REFERENCES REVIEWER (ReviewerEmailAddr));

CREATE TABLE SUBMITS_PAPER (PaperId INT NOT NULL, AuthorId VARCHAR(50) NOT NULL, FOREIGN KEY (PaperId) REFERENCES PAPER (Id), FOREIGN KEY (AuthorId) REFERENCES AUTHOR (EmailAddr));

CREATE TABLE ASSIGNED_REVIEWER (PaperId INT NOT NULL, ReviewerId VARCHAR(50) NOT NULL, FOREIGN KEY (PaperId) REFERENCES PAPER(Id), FOREIGN KEY (ReviewerId) REFERENCES REVIEWER (ReviewerEmailAddr));

CREATE TABLE SUBMITS_REVIEW (Id INT NOT NULL, ReviewerId VARCHAR(50), FOREIGN KEY (Id) REFERENCES REVIEW (Id), FOREIGN KEY (ReviewerId) REFERENCES REVIEWER (ReviewerEmailAddr));

CREATE TABLE HAS (Id INT NOT NULL, ReviewerId VARCHAR(50) NOT NULL, FOREIGN KEY (Id) REFERENCES Topic (Id), FOREIGN KEY (ReviewerId) REFERENCES REVIEWER (ReviewerEmailAddr));
